name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE_NAME .
        docker tag $DOCKER_IMAGE_NAME <docker-registry-url>/$DOCKER_IMAGE_NAME
        docker push <docker-registry-url>/$DOCKER_IMAGE_NAME
    
    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
        kubectl set image deployment/<deployment-name> <container-name>=$DOCKER_IMAGE_NAME
